name: TikTok Downloader

on:
  workflow_dispatch:
    inputs:
      url:
        description: "Link TikTok"
        required: true

jobs:
  download:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install requests beautifulsoup4

      - name: Run downloader
        run: python ttdownload.py <<< "${{ github.event.inputs.url }}"

      - name: Upload result
        uses: actions/upload-artifact@v3
        with:
          name: video
          path: tiktok_no_watermark.mp4
